### ISSUE TITLE
Add Vizality support

### ISSUE THREAD

**Issue by valentinegb** [Discord-Custom-Covers/usrbg#176]
Currently, this doesn't work on Vizality. All that needs to be done is to account for `vz-user-id`. For example:
```css
/*Liam The Protogen#2501*/

[user_by_bdfdb="441384103946878987"],
[data-user-id="441384103946878987"],
[vz-user-id="441384103946878987"] { /* <---- */
  --user-background: url('https://i.imgur.com/LmSsqxG.jpg'); 
}
```
